PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE qa (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    source TEXT
, manual_name TEXT, page_numbers TEXT);
INSERT INTO qa VALUES(1,'What is the primary purpose of the DOE General Employee Radiological Training (GERT)?','The primary purpose of GERT is to provide DOE site employees with knowledge and skills in radiological fundamentals, commensurate with their assigned duties and potential hazards, ensuring safety and compliance with radiological requirements.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(2,'What are the four types of ionizing radiation?','The four types of ionizing radiation are alpha particles, beta particles, neutrons, and gamma rays.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(3,'What is the DOE whole-body radiation dose limit for general employees?','The DOE whole-body radiation dose limit for general employees is 5,000 millirem per year.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(4,'What is the annual background radiation dose to a member of the general population?','The annual background radiation dose to a member of the general population is approximately 360 millirem.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(5,'How does exposure to radiation differ from radioactive contamination?','Exposure to radiation does not result in contamination. Radioactive contamination occurs when uncontained radioactive material is in an unwanted location, potentially contaminating the skin or clothing.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(6,'What is ALARA, and why is it important?','ALARA stands for ''As Low As Reasonably Achievable.'' It is a safety principle aimed at minimizing radiation exposures and releases of radioactive materials by employing all reasonable methods.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(7,'What is the purpose of a Radiation Work Permit (RWP)?','An RWP outlines special instructions, radiation levels, and protective measures required for specific tasks in radiological areas.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(8,'What are some naturally occurring sources of radiation?','Naturally occurring sources of radiation include cosmic radiation, radon gas, terrestrial radiation from the earth''s crust, and radioactive materials within the human body like Potassium-40.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(9,'What is the recommended radiation dose limit for the embryo/fetus of a declared pregnant worker?','The recommended radiation dose limit for the embryo/fetus of a declared pregnant worker is 500 millirem for the period from conception to birth.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(10,'What is the primary contributor to natural background radiation exposure?','Radon gas, which originates from naturally occurring uranium in the soil, is the primary contributor to natural background radiation exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(11,'What is ionizing radiation?','Ionizing radiation is a form of energy that can remove tightly bound electrons from atoms, creating ions.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(12,'How does alpha radiation differ from beta radiation?','Alpha radiation consists of heavy, positively charged particles, while beta radiation consists of lighter, negatively charged particles (electrons).','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(13,'What protective measures are used against alpha radiation?','Protective measures include wearing gloves and respirators to prevent ingestion or inhalation.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(14,'What materials are effective at shielding gamma radiation?','Dense materials such as lead and concrete are effective at shielding gamma radiation.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(15,'What is the purpose of dosimetry?','Dosimetry measures and records the amount of radiation exposure an individual receives.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(16,'What are the three principles of radiation protection?','The three principles are time, distance, and shielding.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(17,'Why is time important in radiation protection?','Limiting the time spent near a radiation source reduces exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(18,'How does distance help in radiation protection?','Increasing distance from a radiation source reduces exposure due to the inverse square law.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(19,'What is a controlled area in radiological terms?','A controlled area is a location where radiological conditions are monitored, and access is restricted.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(20,'What is a dosimeter, and how is it used?','A dosimeter is a device worn to measure an individual’s radiation exposure over time.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(21,'What should you do if your dosimeter shows unexpected high exposure?','Report immediately to the Radiological Control organization for further investigation.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(22,'What does ''background radiation'' mean?','Background radiation refers to the natural levels of radiation present in the environment.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(23,'What is a Radiation Area?','A Radiation Area is a location where radiation levels exceed 5 millirem per hour but do not exceed 100 millirem per hour.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(24,'What is neutron radiation, and where is it encountered?','Neutron radiation consists of uncharged particles and is commonly found in nuclear reactors.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(25,'What is a contamination survey?','It is an assessment to detect and measure radioactive contamination on surfaces or equipment.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(26,'What are the three categories of radioactive waste?','The three categories are low-level waste, high-level waste, and transuranic waste.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(27,'What actions should you take if you find radioactive contamination on your clothing?','Report immediately, avoid spreading contamination, and follow decontamination procedures.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(28,'What is the biological half-life of a radionuclide?','The biological half-life is the time it takes for half of a radionuclide to be eliminated from the body.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(29,'What is acute radiation syndrome (ARS)?','ARS is a serious illness caused by a high dose of radiation over a short period, leading to symptoms like nausea, fatigue, and skin burns.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(30,'How is radiological safety training conducted at DOE sites?','Training is conducted through classroom instruction, practical exercises, and written assessments.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(31,'What is the role of shielding in radiation protection?','Shielding absorbs or blocks radiation to protect personnel from exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(32,'What should you do if you lose your dosimeter?','Report the loss immediately to the Radiological Control Organization and follow their instructions.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(33,'What is the primary goal of radiological safety training for uranium facilities?','To provide personnel with a basic understanding of uranium characteristics and precautions needed for safe work in uranium facilities.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(34,'What are the three natural isotopes of uranium?','Uranium-234, Uranium-235, and Uranium-238.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(35,'What is ''yellowcake''?','Yellowcake is a concentrated uranium oxide produced during the milling process.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(36,'What is uranium hexafluoride (UF6) used for in the nuclear fuel cycle?','UF6 is used for uranium enrichment during the nuclear fuel cycle.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(37,'What are the two primary decay series of uranium?','The actinium series (Uranium-235) and the uranium series (Uranium-238).','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(38,'What is the primary health risk associated with uranium inhalation?','Damage to the lungs and kidneys due to uranium''s chemical toxicity and radiation.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(39,'What precautions should be taken when handling uranium chips and filings?','Submerge them in water or mineral oil to prevent spontaneous ignition.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(40,'How is uranium oxide color related to its solubility?','Darker uranium oxides are less soluble, while lighter oxides are more soluble.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(41,'What is depleted uranium?','Uranium with a reduced amount of Uranium-235, primarily composed of Uranium-238.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(42,'What does the term ''criticality'' refer to in nuclear safety?','A self-sustaining nuclear chain reaction.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(43,'What are the main uses of enriched uranium?','Nuclear reactor fuel, nuclear weapons, and naval propulsion reactors.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(44,'What are uranium mill tailings?','Residual waste left after uranium ore has been processed to extract yellowcake.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(45,'What is the biological half-life of uranium in the body?','It ranges from 6 to 5000 days depending on the organ affected.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(46,'How does uranium emit radiation?','Through alpha particle emission or nuclear fission.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(47,'What is the purpose of uranium enrichment?','To increase the proportion of Uranium-235 for use in reactors and weapons.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(48,'What are common safety measures for preventing uranium fires?','Using MET-L-X powder and water submersion.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(49,'How is uranium-235 different from uranium-238?','Uranium-235 is fissile with thermal neutrons, whereas Uranium-238 is not.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(50,'What is the PUREX process?','A chemical process for extracting plutonium and uranium from spent nuclear fuel.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(51,'What is high-level waste (HLW)?','Highly radioactive waste from reprocessing spent nuclear fuel.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(52,'Why is radon considered hazardous?','It is a radioactive gas that can accumulate indoors and cause lung cancer.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(53,'What is the primary protective measure against inhaling uranium dust?','Using respiratory protection and maintaining clean work environments.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(54,'What is the purpose of a radiological control technician (RCT)?','To monitor and manage radiation safety in facilities handling radioactive materials.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(55,'What does ''alpha radiation'' mean for external dose hazard?','Alpha radiation poses minimal external hazard due to its short range.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(56,'What does the acronym UMTRA stand for?','Uranium Mill Tailings Remedial Action.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(57,'What is the significance of Uranium-233?','It is a fissile material manufactured by irradiating Thorium-232.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(58,'What material is used to fabricate reactor fuel rods?','Uranium dioxide (UO2).','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(59,'What is the chemical symbol for uranium tetrafluoride?','UF4.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(60,'How is uranium ore typically processed?','Through crushing, grinding, leaching, and purification.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(61,'What are common byproducts of uranium mining?','Mill tailings and radioactive dust.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(62,'What safety precautions are necessary for UF6 storage?','Ensure containment and avoid moisture to prevent HF gas production.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(63,'How does uranium exposure affect bones?','Uranium tends to accumulate in bone tissue, posing a radiological hazard.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(64,'What is the significance of Uranium-232?','It is a byproduct of Uranium-233 production and contributes to gamma radiation hazards.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(65,'What is the minimum passing score for radiological training tests?','80%, with adjustments based on statistical analysis.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(66,'What equipment is essential for radiological training?','Overhead projectors, screens, flip charts, and visual aids.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(67,'What are the principal uses of depleted uranium?','Radiation shielding, armor-piercing munitions, and counterweights.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(68,'What is a key feature of uranium hydride?','It is used for tritium storage.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(69,'What does a uranium criticality monitor do?','Detects and alarms criticality incidents.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(70,'How are mill tailings managed?','Through containment and environmental remediation programs like UMTRA.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(71,'Why is hydrogen fluoride (HF) dangerous?','It is corrosive and can cause severe damage to lungs and skin.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(72,'What color indicates highly soluble uranium compounds?','Yellow or orange.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(73,'What are the primary isotopes used in nuclear power?','Uranium-235 and Uranium-238.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(74,'How does uranium toxicity compare to its radiological hazard?','Acute exposure often leads to toxic effects, while chronic exposure poses radiological risks.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(75,'What regulatory document outlines uranium training standards?','DOE-STD-1098-99, Radiological Control (RCS).','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(76,'How often should radiological training be refreshed?','Every two years if meeting 10 CFR 835 requirements.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(77,'What is Uranium-236 and where is it found?','A byproduct of Uranium-235 in reactors, found in reprocessed nuclear fuel.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(78,'What are typical hazards of uranium solution spills?','Increased criticality risk and spread of contamination.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(79,'What are uranium ''decay products''?','Radioactive elements formed as uranium isotopes decay.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(80,'How are uranium fire hazards managed?','By submersing reactive materials in water or mineral oil.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(82,'What is the role of a Radiological Safety Officer (RSO)?','To oversee radiological safety practices and compliance.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(83,'What is the primary goal of radiological protection in occupational settings?','To ensure the safety and health of workers by minimizing exposure to ionizing radiation while performing their duties.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(84,'What are the three basic principles of radiation protection?','Justification, Optimization (ALARA), and Dose Limitation.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(85,'What does ALARA stand for?','As Low As Reasonably Achievable.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(86,'Why is justification important in radiation protection?','Justification ensures that any exposure to radiation results in a net benefit to workers or society.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(88,'What is a controlled area in radiation protection?','An area where access is controlled to protect individuals from potential radiation exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(89,'What is a monitored area?','An area where radiation levels are regularly assessed but do not require strict access control.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(90,'How often should dosimeters be calibrated?','At regular intervals specified by regulatory standards.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(91,'What is the importance of workplace monitoring?','To detect and assess radiation levels and ensure the effectiveness of protective measures.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(92,'What is the purpose of personal dosimetry?','To measure and record an individual worker’s radiation exposure over time.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(93,'What are the three main sources of occupational radiation exposure?','External radiation, internal contamination, and radioactive waste.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(94,'What are the key steps in contamination control?','Prevent, detect, and contain contamination to protect workers and the environment.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(95,'What is the difference between external and internal contamination?','External contamination occurs on the skin or clothing, while internal contamination happens through ingestion, inhalation, or wounds.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(96,'Why is proper labeling of radioactive materials important?','To ensure clear identification of hazards and proper handling.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(97,'What does a Radiation Work Permit (RWP) provide?','It provides guidelines for safe work practices in radiological areas.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(98,'What is the recommended limit for whole-body occupational exposure per year?','5,000 millirem (50 millisieverts).','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(99,'What measures are recommended to minimize radiation exposure in the workplace?','Time management, distance from sources, and effective shielding.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(100,'How can workers ensure contamination does not spread outside a controlled area?','By using appropriate containment methods and monitoring exits for contamination.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(101,'What is the purpose of regular training in radiological protection?','To keep workers informed about hazards and reinforce safe practices.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(102,'What are radioactive waste disposal guidelines?','Proper segregation, labeling, storage, and disposal following regulatory standards.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(103,'Why is ventilation important in radiological areas?','To prevent the buildup of airborne radioactive materials.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(104,'What is the function of an air sampler in radiological areas?','To detect and measure airborne radioactive particles.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(105,'What is a derived air concentration (DAC)?','The concentration of a radionuclide in air that would result in an annual dose limit if inhaled continuously.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(106,'What is the purpose of health physics surveys?','To assess radiation levels, contamination, and worker safety in operational areas.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(107,'What should workers do if they suspect radiation exposure above permissible limits?','Immediately report to the radiological control team and follow emergency procedures.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(108,'What is criticality safety?','Measures to prevent an unintended self-sustaining nuclear chain reaction.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(109,'What are hot particles?','Small radioactive particles with high activity levels.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(110,'What are the potential effects of acute radiation exposure?','Nausea, fatigue, skin burns, and in severe cases, damage to internal organs.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(111,'What role do supervisors play in radiological protection?','Supervisors ensure workers follow safety protocols and maintain compliance.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(112,'What is the purpose of radiation warning signs?','To alert personnel of the presence of radiation or radioactive materials.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(113,'How is radioactive waste classified?','As low-level, intermediate-level, or high-level waste based on activity and hazard.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(115,'Why is hygiene important in radiological work areas?','To prevent ingestion or inhalation of radioactive materials.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(116,'What is a high-radiation area?','An area where radiation levels exceed 100 millirem per hour.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(117,'How does time management reduce radiation exposure?','Reducing time spent near radiation sources minimizes accumulated dose.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(118,'What is a decontamination station?','A location designed for the removal of radioactive contamination from workers or equipment.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(119,'What is the annual dose limit for pregnant workers?','500 millirem (5 millisieverts) to the fetus.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(120,'Why is proper storage of radioactive materials critical?','To prevent unauthorized access, contamination, and exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(121,'What is a controlled zone?','An area with additional safety measures due to elevated radiation levels.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(122,'How is contamination on the skin measured?','Using handheld contamination monitors or wipes.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(123,'What is neutron radiation?','A type of radiation consisting of neutral particles emitted during fission reactions.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(124,'How is a radiation dose measured?','Using units such as millirem or millisieverts.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(125,'What should workers do during a radiological emergency?','Evacuate as instructed and report to designated emergency response locations.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(126,'What is the primary role of radiological control technicians (RCTs)?','To monitor radiation levels, contamination, and compliance with safety protocols.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(127,'What is an unrestricted area?','An area where radiation levels do not pose significant risk and are open to general access.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(128,'What is the purpose of periodic health checks for radiological workers?','To monitor potential long-term effects of radiation exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(129,'What is the importance of regular instrument calibration?','To ensure accurate measurements of radiation and contamination levels.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(130,'How does distance reduce radiation exposure?','Increasing distance decreases exposure according to the inverse square law.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(131,'What is the purpose of radiation shielding?','To absorb or block radiation to protect workers from exposure.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(132,'What are some examples of personal protective equipment (PPE) in radiological areas?','Gloves, respirators, face shields, and protective clothing.','JSON Dataset',NULL,NULL);
INSERT INTO qa VALUES(133,'What is uranium?','Uranium is a radioactive element','Database',NULL,NULL);
INSERT INTO qa VALUES(134,'What is a safety protocol?','A safety protocol ensures safe handling of materials.','Database',NULL,NULL);
INSERT INTO sqlite_sequence VALUES('qa',134);
CREATE INDEX idx_question ON qa(question);
COMMIT;
